executor: docker-node
steps:
  - restore-infra-workspace
  - run:
      name: 'Terraform Init'
      command: yarn cli terraform --stage=prod init
  - run:
      name: 'Terraform Apply'
      command: yarn cli terraform --stage=prod apply
