executor: docker-node-neo4j
resource_class: large
steps:
  - restore-workspace
  # - checkout
  - run:
      name: 'Install Vercel CLI'
      command: npm install --global vercel@latest
  - run:
      name: 'Pull Vercel Environment Information'
      command: vercel pull --yes --environment=production --token=$VERCEL_ACCESS_TOKEN
  - run:
      name: 'Build Project Artifacts'
      command: vercel build -c prod --token=$VERCEL_ACCESS_TOKEN
  - run:
      name: 'Deploy Project Artifacts to Vercel'
      command: vercel deploy --prebuilt -c prod --token=$VERCEL_ACCESS_TOKEN
