/* eslint-disable canonical/sort-keys */

export const ENV_VARS = {
  VERCEL_ENV: 'VERCEL_ENV',
  NEXT_PUBLIC_VERCEL_ENV: 'NEXT_PUBLIC_VERCEL_ENV',
  NEXT_PUBLIC_PLATFORM_HOST: 'NEXT_PUBLIC_PLATFORM_HOST',

  // Auth0
  AUTH0_AUDIENCE: 'AUTH0_AUDIENCE',
  AUTH0_ISSUER_BASE_URL: 'AUTH0_ISSUER_BASE_URL',
  AUTH0_CLIENT_ID: 'AUTH0_CLIENT_ID',
  AUTH0_CLIENT_SECRET: 'AUTH0_CLIENT_SECRET',
  AUTH0_SECRET: 'AUTH0_SECRET',

  // Auth0 user
  AUTH0_CYPRESS_USERNAME: 'AUTH0_CYPRESS_USERNAME',
  AUTH0_CYPRESS_PASSWORD: 'AUTH0_CYPRESS_PASSWORD',

  // CI
  CI: 'CI',

  // System
  NODE_ENV: 'NODE_ENV',
}
