nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: EE2242B7-FC5E-4CC0-9630-F83CE6524319
    npmRegistryServer: 'https://npm.fontawesome.com/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.4.0/bundles/@yarnpkg/plugin-after-install.js'

afterInstall: ./scripts/yarn/after-install.sh

yarnPath: .yarn/releases/yarn-3.5.1.cjs
