description: 'Build Repo'
steps:
  - restore_cache:
      name: 'Restore NX Cache'
      keys:
        - nx-cache-{{ checksum "node_modules/.cache/nx/lockfile.hash" }}
        - nx-cache
  - run:
      name: 'Monitor NX Cache Size'
      command: ./scripts/nx/reset-cache.sh
  # Can't use `yarn cli` doesn't exist yet
  - run: npx nx run-many --target=build --projects=platform,platform-api,cli,landing,websites --parallel=4 -c ci --verbose --nx-bail
  - save_cache:
      name: 'Save Cache'
      key: nx-cache-{{ checksum "node_modules/.cache/nx/lockfile.hash" }}
      paths:
        - ~/project/dist/apps/platform/.next/cache
        - ~/project/dist/apps/platform-api/.next/cache
        - ~/project/dist/apps/landing/.next/cache
        - ~/project/dist/apps/websites/.next/cache
    # This step needs to be after reset-cache
  - save_cache:
      name: 'Save NPM Cache'
      key: node-modules-{{ checksum "yarn.lock" }}
      paths:
        - ~/project/node_modules
        # Need this folder for local cache to hit, remote cache still hits but takes too long to build
        # - ~/project/node_modules/.cache/nx
