steps:
  # NPM cache already restored in restore-workspace, which is shared with other jobs. While yarn cache is only needed in the setup-workspace job
  # The time to restore node_modules is longer than the time saving from installing node_modules again
  # - restore_cache:
  #     name: 'Restore NPM Cache'
  #     keys:
  #       - node-modules-{{ checksum "yarn.lock" }}
  - restore_cache:
      name: 'Restore Yarn Cache'
      keys:
        - yarn-cache-{{ checksum "yarn.lock" }}
        - yarn-cache
  - run:
      name: 'Install NPM Packages'
      command: yarn install --immutable
  - save_cache:
      name: 'Save Yarn Cache'
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.yarn
  # node_modules cache needs to be checked for cache reset before we can save, otherwise nx cache grows too much. This step happens after build
