blank_issues_enabled: true
contact_links:
  # - name: Read the Community Guidelines
  #   about: "Please make sure you have read the submission guidelines before posting an issue"
  #   url: https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-an-issue
  # - name: Have a question?
  #   url: https://join.slack.com/t/nrwlcommunity/shared_invite/enQtNzU5MTE4OTQwOTk0LTgxY2E0ZWYzMWE0YzA5ZDA2MWM1NDVhNmI2ZWMyYmZhNWJiODk3MjkxZjY3MzU5ZjRmM2NmNWU1OTgyZmE4Mzc
  #   about: "The Community Slack is a great place for questions to be asked and answered. Please use the #support channel if you need help with your workspace!"
  # - name: Are you looking for integration with a new tool?
  #   url: https://nx.dev/nx-community
  #   about: "There are a lot of awesome Plugins for Nx provided by the community! Check here to see if there is a community plugin to integrate your tool."
