export * from './resource.dto.interface'
export * from './resource.model.interface'
export * from './resource.ref'
export * from './resource.repo.interface'
export * from './resource.service.interface'
